version: "3.9"

services:
  db-users:
     image: postgres:15.2
     restart: always
     ports:
        - 5433:5432
     environment:
        - POSTGRES_USER=security
        - POSTGRES_PASSWORD=security
        - POSTGRES_DB=users
     networks:
        - config_custom-app-network
  
  app-users:
     build: ./
     ports:
        - 8083:8083
     networks:
        - config_custom-app-network
        
networks:
   config_custom-app-network:
      external: true
