version: "3.9"

services:
  db-users:
     image: postgres:15.2
     restart: always
     ports:
        - 5433:5432
     environment:
        - POSTGRES_USER=security
        - POSTGRES_PASSWORD=security
        - POSTGRES_DB=users
