spring:
   profiles:
      active: dev
      
---

spring:
   config:
      activate:
         on-profile: prod
   
#Spring Security settings for username and password client base authentication
   security:
      client-authentication:
         username: ConnectionProdClient
         password: connectionProdClient
         
server:
   port: 8083

connection:
   db:
      driverClassName: org.postgresql.Driver
      jdbcUrl: jdbc:postgresql://db-users:5432/users?charSet=utf-8
      username: security
      password: security
      maxPoolSize: 3
      connectionTimeout: 3000
   hibernate:
      schema: none
      sessionContext: thread
      dialect: org.hibernate.dialect.PostgreSQLDialect
      showSql: true
      transactionIsolationValue: 2
                  
---

spring:
   config:
      activate:
         on-profile: dev
   
#Spring Security settings for username and password client base authentication
   security:
      client-authentication:
         username: ConnectionDevClient
         password: connectionDevClient
         
server:
   port: 8083

connection:
   db:
      driverClassName: org.postgresql.Driver
      jdbcUrl: jdbc:postgresql://localhost:5433/users?charSet=utf-8
      username: security
      password: security
      maxPoolSize: 3
      connectionTimeout: 3000
   hibernate:
      schema: none
      sessionContext: thread
      dialect: org.hibernate.dialect.PostgreSQLDialect
      showSql: true
      transactionIsolationValue: 2
      

---      

spring:
   config:
      activate:
         on-profile: test
         
#Spring Security test settings for username and password client base authentication
   security:
      client-authentication:
         username: ConnectionTestClient
         password: connectionTestClient

connection:
   db:
      driverClassName: org.postgresql.Driver
      jdbcUrl: ${db_url}
      username: ${db_user}
      password: ${db_password}
      maxPoolSize: 3
      connectionTimeout: 3000
   hibernate:
      schema: none
      sessionContext: thread
      dialect: org.hibernate.dialect.PostgreSQLDialect
      showSql: true
      transactionIsolationValue: 2
testcontainers:
   postgresqlDockerImage: postgres:15.2
   jdbcUrlEnvVar: db_url
   usernameEnvVar: db_user
   passwordEnvVar: db_password
   liquibaseChangelogFile: /liquibase/db-test-users-changelog.xml
         