# Choose active spring config: prod | dev
spring:
   profiles:
      active: prod
      
   application:
      name: user      
      
---

spring:
   config:
      activate:
         on-profile: dev
      
      import: configserver:http://localhost:8090

---

spring:
   config:
      activate:
         on-profile: prod
   
      import: configserver:http://app-config:8090
